# Generated by Django 2.2.16 on 2021-11-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'jupyter_machine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kernel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LdapGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ldap_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RangerHivePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(
                    choices=[('default_user', 'default_user'),
                             ('default_cse', 'default_cse'),
                             ('default_dsip', 'default_dsip'),
                             ('default_bdr', 'default_bdr')], max_length=63)),
                ('db', models.CharField(max_length=63, null=True)),
                ('db_tables', models.CharField(max_length=63, null=True)),
                ('db_imagerie', models.CharField(max_length=63, null=True)),
                ('db_work', models.CharField(max_length=63, null=True)),
            ],
            options={
                'db_table': 'ranger_hive_policy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=63, unique=True)),
                ('name', models.CharField(blank=True, max_length=63,
                                          null=True)),
                ('firstname', models.CharField(blank=True, max_length=63,
                                               null=True)),
                ('lastname', models.CharField(blank=True, max_length=63,
                                              null=True)),
                ('mail', models.CharField(blank=True, max_length=63,
                                          null=True)),
                ('gid', models.BigIntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=63,
                                           null=True)),
                ('home', models.TextField()),
                ('conda_enable', models.BooleanField(default=False)),
                ('conda_py_version', models.CharField(blank=True, default='3.7',
                                                      max_length=64)),
                ('conda_r', models.BooleanField(default=False)),
                ('ssh', models.BooleanField(default=False)),
                ('brat_port', models.IntegerField(null=True)),
                ('tensorboard_port', models.IntegerField(null=True)),
                ('airflow_port', models.IntegerField(null=True)),
                ('db_imagerie', models.BooleanField(default=False)),
                ('aphp_ldap_group_dn', models.CharField(max_length=255)),
                ('spark_port_start', models.IntegerField()),
                ('jupyter_machines', models.ManyToManyField(
                    related_name='users_uids',
                    to='workspaces.JupyterMachine')),
                ('kernel', models.ManyToManyField(
                    related_name='users_uids', to='workspaces.Kernel')),
                ('ldap_groups', models.ManyToManyField(
                    blank=True, null=True, related_name='users_uids',
                    to='workspaces.LdapGroup')),
                ('ranger_hive_policy', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='users_uids',
                    to='workspaces.RangerHivePolicy')),
            ],
            options={
                'db_table': 'cse_account',
                'managed': True,
            },
        ),
    ]
