# Generated by Django 2.2.16 on 2021-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='kernel',
            new_name='kernels',
        ),
        migrations.RenameField(
            model_name='ldapgroup',
            old_name='machine',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='ldap_groups',
            field=models.ManyToManyField(blank=True, related_name='users_uids',
                                         to='workspaces.LdapGroup'),
        ),
    ]
