# Generated by Django 2.2.16 on 2021-12-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20211105_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(
                    choices=[('default_user', 'default_user'),
                             ('default_cse', 'default_cse'),
                             ('default_dsip', 'default_dsip'),
                             ('default_bdr', 'default_bdr')], max_length=63)),
                ('identifier', models.CharField(max_length=63, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=63)),
                ('title', models.TextField(blank=True)),
                ('thematic', models.CharField(blank=True, max_length=63)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(
                    choices=[('new', 'new'), ('validated', 'validated'),
                             ('not_validated', 'not_validated'),
                             ('aborted', 'aborted'),
                             ('in progress', 'in progress'),
                             ('closed', 'closed')],
                    default='new', max_length=20)),
                ('operation_actors', models.TextField(blank=True)),
                ('partners', models.TextField(blank=True)),
                ('lawfulness_of_processing', models.TextField(blank=True)),
                ('data_recipients', models.TextField(blank=True)),
                ('data_conservation_duration', models.DurationField(null=True)),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('validation_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                to='workspaces.Project'),
        ),
    ]
