# Generated by Django 2.2.16 on 2022-06-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20211214_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jupytermachine',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kernel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ldapgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rangerhivepolicy',
            options={},
        ),
        migrations.AlterModelTable(
            name='account',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jupytermachine',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kernel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ldapgroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rangerhivepolicy',
            table=None,
        ),
    ]
