image: $IMAGE_REPOSITORY_URL/python:$CI_COMMIT_BRANCH

default:
  tags:
    - $GITLAB_RUNNER_TAG

stages:
  - build
  - test
  - deploy
  - release

.default_rules:
  rules:
    - if: ($CI_COMMIT_BRANCH =~ $STANDARD_CD_BRANCHES || $CI_COMMIT_BRANCH =~ $PROTECTED_CD_BRANCHES) && $ONLY_RELEASE == null
    - when: never

.release_rules:
  rules:
    - if: ($CI_COMMIT_BRANCH =~ $STANDARD_CD_BRANCHES && $ENABLE_RELEASE == "true"
    - if: ($CI_COMMIT_BRANCH =~ $PROTECTED_CD_BRANCHES && $ENABLE_RELEASE == "true"
      when: manual
    - when: never

build:
  stage: build
  before_script:
    - pip install flake8
  script:
    - echo "test lint"
#    - flake8 cohort/
#    - flake8 cohort_back/
#    - flake8 explorations/
  rules:
    - !reference [.default_rules, rules]

test:
  stage: test
  before_script:
    - apt-get update
    - pip install -r requirements.txt
  script:
    - echo "Testing the code"
#    - cd tests/ && pytest -v
  rules:
    - !reference [.default_rules, rules]

deploy:
  image :
    name : $IMAGE_REPOSITORY_URL/kaniko-executor:$CI_COMMIT_BRANCH
    entrypoint : [ "" ]
  stage: deploy
  script:
    - sh .gitlab/deployment.sh
  rules:
    - !reference [.default_rules, rules]

release:
  image:
    name: $IMAGE_REPOSITORY_URL/alpine:$CI_COMMIT_BRANCH
    entrypoint: [ "" ]
  stage: release
  script:
    - bash .gitlab/release.sh
  rules:
    - !reference [.release_rules, rules]