image: harbor.eds.aphp.fr/cohort360/python:3.7.10

variables:
  PIP_EXTRA_CLI_PARAMETERS: "--proxy=http:\\/\\/proxym-inter.aphp.fr:8080"
  TEMPLATE_REGISTRY_HOST: 'registry.gitlab.com'
  SECURE_ANALYZERS_PREFIX: "$TEMPLATE_REGISTRY_HOST/security-products"
  SAST_IMAGE_SUFFIX: ""

stages:
  - lint
  - test
  - compliance
  - deploy

lint-job:
  stage: lint
  before_script:
    - pip install flake8
  script:
    - echo "test lint"
    - flake8 accesses/ admin_cohort/ cohort/ workspaces/ exports/ --max-line-length 150
  allow_failure: false

test-job:
  image: harbor.eds.aphp.fr/cohort360/python-test:3.8.1
  stage: test
  services:
    - postgres
  variables:
    POSTGRES_DB: portail_dev
    POSTGRES_USER: portail_dev_limited_rw
    POSTGRES_PASSWORD: portail_psswd
  script:
    - cp admin_cohort/.test.env admin_cohort/.env
    - pip install -r requirements.txt
    - coverage run --source='.' --omit="*/test*","*/migrations/*" manage.py test exports cohort workspaces
    - coverage xml --omit="*/test*","*/migrations/*" -o coverage.xml
    - coverage html --omit="*/test*","*/migrations/*" -d htmlcov
  artifacts:
    expire_in: 7 days
    paths:
      - htmlcov/
      - coverage.xml
      - report.html
      - report.xml
  only:
    - tags
    - develop

deploy-job:
  image: harbor.eds.aphp.fr/cohort360/kaniko:debug
  stage: deploy
  script:
    - export VERSION=$(cat ./admin_cohort/__init__.py | grep __version__ | head -1 | awk -F'=' '{ print $2 }' | sed "s/[' ]//g")
    - mkdir -p /kaniko/.docker
    - |-
      KANIKOPROXYARGS=""
      KANIKOCFG="\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${BOT_NAME}\",\"password\":\"${BOT_TOKEN}\"}}"
      if [ "x${http_proxy}" != "x" -o "x${https_proxy}" != "x" ]; then
        KANIKOCFG="${KANIKOCFG}, \"proxies\" : { \"default\" : { \"httpProxy\" : \"${http_proxy}\", \"httpsProxy\" : \"${https_proxy}\", \"noProxy\" : \"${no_proxy}\" } }"
        KANIKOPROXYARGS="--build-arg http_proxy=${http_proxy} --build-arg https_proxy=${https_proxy} --build-arg no_proxy=${no_proxy}"
      fi
      KANIKOCFG="{ ${KANIKOCFG} }"
      echo "${KANIKOCFG}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      $KANIKOPROXYARGS
      --destination "${CI_REGISTRY_IMAGE}:${VERSION}"
  only:
    - tags
    - develop
    - ^feat_deploy_(\w*|\d*)

iac-sast:
  stage: test
  artifacts:
    name: sast
    paths:
      - gl-sast-report.json
    when: always
  rules:
    - when: never
  # `rules` must be overridden explicitly by each child job
  # see https://gitlab.com/gitlab-org/gitlab/-/issues/218444
  variables:
    SEARCH_MAX_DEPTH: 4
  allow_failure: true
  script:
    - /analyzer run

kics-iac-sast:
  extends: iac-sast
  image:
    name: "$SAST_ANALYZER_IMAGE"
  variables:
    SAST_ANALYZER_IMAGE_TAG: 3
    SAST_ANALYZER_IMAGE: "$SECURE_ANALYZERS_PREFIX/kics:$SAST_ANALYZER_IMAGE_TAG$SAST_IMAGE_SUFFIX"
  rules:
    - if: $SAST_DISABLED
      when: never
    - if: $SAST_EXCLUDED_ANALYZERS =~ /kics/
      when: never
    - if: $CI_COMMIT_BRANCH


Enforce Compliance:
  stage: Compliance
  before_script:
    - apk add jq
  script:
    - jq -r '.vulnerabilities[] | select(.severity == "Critical") | (.severity, .message, .location, .identifiers[].url)' gl-sast-report.json > results.txt
    - jq -r '.vulnerabilities[] | select(.severity == "High") | (.severity, .message, .location, .identifiers[].url)' gl-sast-report.json >> results.txt
    - jq -r '.vulnerabilities[] | select(.severity == "Medium") | (.severity, .message, .location, .identifiers[].url)' gl-sast-report.json >> results.txt
    - chmod u+x check-sast-results.sh
    - ./check-sast-results.sh