# Generated by Django 2.2.9 on 2021-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128,
                                              verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True,
                                                    verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('provider_username', models.IntegerField(
                    primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(
                    max_length=254, null=True, unique=True,
                    verbose_name='email address')),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CareSite',
            fields=[
                ('key', models.TextField(blank=True, null=True)),
                ('insert_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('update_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('delete_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('change_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('care_site_id', models.BigIntegerField(primary_key=True,
                                                        serialize=False)),
                ('care_site_source_value', models.TextField(blank=True,
                                                            null=True)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('care_site_name', models.TextField(blank=True, null=True)),
                ('care_site_short_name', models.TextField(blank=True,
                                                          null=True)),
                ('place_of_service_concept_id', models.IntegerField(blank=True,
                                                                    null=True)),
                ('place_of_service_source_value', models.TextField(blank=True,
                                                                   null=True)),
                ('place_of_service_source_concept_id', models.IntegerField(
                    blank=True, null=True)),
                ('valid_start_date', models.DateField(blank=True, null=True)),
                ('valid_end_date', models.DateField(blank=True, null=True)),
                ('care_site_type_concept_id', models.IntegerField(blank=True,
                                                                  null=True)),
                ('care_site_type_source_value', models.TextField(blank=True,
                                                                 null=True)),
                ('care_site_type_source_concept_id', models.IntegerField(
                    blank=True, null=True)),
                ('cdm_source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'care_site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('key', models.TextField(blank=True, null=True)),
                ('insert_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('update_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('delete_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('provider_id', models.BigIntegerField(primary_key=True,
                                                       serialize=False)),
                ('provider_name', models.TextField(blank=True, null=True)),
                ('npi', models.TextField(blank=True, null=True)),
                ('dea', models.TextField(blank=True, null=True)),
                ('specialty_concept_id', models.IntegerField(blank=True,
                                                             null=True)),
                ('care_site_id', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('year_of_birth', models.BigIntegerField(blank=True,
                                                         null=True)),
                ('gender_concept_id', models.IntegerField(blank=True,
                                                          null=True)),
                ('provider_source_value', models.TextField(blank=True,
                                                           null=True)),
                ('specialty_source_value', models.TextField(blank=True,
                                                            null=True)),
                ('specialty_source_concept_id', models.IntegerField(blank=True,
                                                                    null=True)),
                ('gender_source_value', models.TextField(blank=True,
                                                         null=True)),
                ('gender_source_concept_id', models.IntegerField(blank=True,
                                                                 null=True)),
                ('firstname', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('cdm_source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provider',
                'managed': True,
            },
        ),
    ]
