# Generated by Django 2.2.16 on 2021-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='care_site_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='dea',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='key',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='npi',
        ),
        migrations.AddField(
            model_name='caresite',
            name='hash',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
