# Generated by Django 4.2.9 on 2024-01-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0002_releasenote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='provider_username',
            new_name='username',
        ),
    ]
