# Generated by Django 2.2.16 on 2021-09-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0002_auto_20210511_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
