# Generated by Django 2.2.16 on 2021-12-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0003_auto_20210915_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareSite',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='cdm_source',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='gender_concept_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='gender_source_concept_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='gender_source_value',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialty_concept_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialty_source_concept_id',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialty_source_value',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='year_of_birth',
        ),
    ]
