# Generated by Django 4.2.11 on 2024-09-02 14:09

import admin_cohort.models.maintenance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0004_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancephase',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maintenancephase',
            name='type',
            field=models.CharField(choices=[(admin_cohort.models.maintenance.MaintenanceType['PARTIAL'], 'Partial'), (admin_cohort.models.maintenance.MaintenanceType['FULL'], 'Full')], default=admin_cohort.models.maintenance.MaintenanceType['PARTIAL'], max_length=10),
        ),
    ]
