# Generated by Django 2.2.16 on 2022-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0004_auto_20211229_1441'),
        ('cohort', '0005_auto_20220405_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='insert_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='update_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider_username',
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_at',
        ),
    ]
