# Generated by Django 5.0.10 on 2024-12-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0005_maintenancephase_message_maintenancephase_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='provider_id',
        ),
    ]
