# Generated by Django 2.2.16 on 2022-03-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0005_auto_20220331_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RunSQL(
            "INSERT INTO \"user\" ("
            "provider_username, provider_id, email, firstname, lastname) "
            "SELECT DISTINCT ON (provider_source_value) provider_source_value, "
            "provider_id, email, firstname, lastname "
            "FROM provider p "
            "ON CONFLICT(provider_username) "
            "DO "
            "UPDATE SET "
            "provider_id=EXCLUDED.provider_id, "
            "email=EXCLUDED.email, "
            "firstname=EXCLUDED.firstname, "
            "lastname=EXCLUDED.lastname;",
            reverse_sql="INSERT INTO provider (provider_source_value, "
                        "provider_id, email, firstname, lastname)"
                        "VALUES(SELECT provider_username, provider_id, "
                        "email, firstname, lastname FROM \"user\")"
        ),
    ]
