# Generated by Django 2.2.16 on 2022-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0006_manual_save_provider_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
