# Generated by Django 2.2.16 on 2022-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0007_auto_20220331_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
