# Generated by Django 5.0.14 on 2026-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0007_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancephase',
            name='is_data_saved_message_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
