# Generated by Django 2.2.16 on 2022-06-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0008_auto_20220719_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePhase',
            fields=[
                ('insert_datetime', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(
                    auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(
                    blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        )
    ]
