# Generated by Django 2.2.16 on 2022-06-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0009_auto_20220609_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
