# Generated by Django 4.1.6 on 2023-02-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_cohort', '0012_alter_user_provider_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
