# Generated by Django 5.0.4 on 2024-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses_perimeters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCohortDef',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(blank=True, db_column='source__type', null=True)),
                ('size', models.BigIntegerField(db_column='_size', null=True)),
                ('source_reference_id', models.BigIntegerField(db_column='_sourcereferenceid', null=True)),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'list',
                'managed': False,
            },
        ),
    ]
