# Generated by Django 5.0.14 on 2025-05-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses_perimeters', '0002_listcohortdef'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactRelationship',
        ),
        migrations.DeleteModel(
            name='ListCohortDef',
        ),
    ]
