# Generated by Django 2.2.16 on 2021-07-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('export_request_id', models.BigAutoField(primary_key=True,
                                                          serialize=False)),
                ('cohort_id', models.BigIntegerField()),
                ('motivation', models.TextField(null=True)),
                ('provider_id', models.BigIntegerField()),
                ('output_format', models.CharField(
                    choices=[('csv', 'csv'), ('hive', 'hive'),
                             ('psql', 'psql')],
                    default='csv', max_length=4)),
                ('status', models.CharField(
                    choices=[('new', 'new'), ('validated', 'validated'),
                             ('not validated', 'not validated'),
                             ('running', 'running'), ('canceled', 'canceled'),
                             ('done', 'done'), ('failed', 'failed'),
                             ('to delete', 'to delete'),
                             ('deleted', 'deleted')],
                    default='new', max_length=20)),
                ('status_info', models.TextField(null=True)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('execution_request_datetime', models.DateTimeField(null=True)),
                ('validation_request_datetime',
                 models.DateTimeField(null=True)),
                ('is_user_notified', models.BooleanField(default=False)),
                ('target_location', models.TextField(null=True)),
                ('target_name', models.TextField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'export_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportRequestTable',
            fields=[
                ('export_request_table_id',
                 models.BigAutoField(primary_key=True, serialize=False)),
                ('omop_table_name', models.TextField()),
                ('source_table_name', models.TextField(null=True)),
                ('export_request', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='tables', to='exports.ExportRequest')),
            ],
            options={
                'db_table': 'export_request_table',
                'managed': True,
            },
        ),
    ]
