# Generated by Django 2.2.16 on 2021-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortDefinition',
            fields=[
                ('cohort_definition_id',
                 models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner_entity_id', models.BigIntegerField()),
                ('owner_domain_id', models.TextField(null=True)),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'cohort_definition',
                'managed': True,
            },
        ),
    ]
