# Generated by Django 2.2.16 on 2022-02-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20211214_1855'),
        ('exports', '0002_cohortdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='creator_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='reviewer_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='target_unix_account',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='export_requests', to='workspaces.Account'),
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='output_format',
            field=models.CharField(
                choices=[('csv', 'csv'), ('hive', 'hive'),
                         ('psql_nomi', 'psql_nomi'),
                         ('psql_pseudo', 'psql_pseudo')],
                default='csv', max_length=20),
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='status',
            field=models.CharField(
                choices=[('new', 'new'), ('validated', 'validated'),
                         ('denied', 'denied'), ('running', 'running'),
                         ('canceled', 'canceled'), ('done', 'done'),
                         ('failed', 'failed'), ('to delete', 'to delete'),
                         ('deleted', 'deleted')], default='new', max_length=20),
        ),
    ]
