# Generated by Django 2.2.16 on 2022-04-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_auto_20220223_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='nominative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='output_format',
            field=models.CharField(choices=[('csv', 'csv'), ('hive', 'hive'),
                                            ('psql', 'psql')],
                                   default='csv', max_length=20),
        ),
    ]
