# Generated by Django 2.2.16 on 2022-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0004_auto_20220401_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='creator_provider_source_value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='provider_source_value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='reviewer_id',
            field=models.TextField(null=True),
        ),
    ]
