# Generated by Django 4.2.9 on 2024-01-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_datalab_name_exporttable_cohort_result_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='name',
        ),
        migrations.AddField(
            model_name='export',
            name='cohort_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
