# Generated by Django 2.2.16 on 2022-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_auto_20220405_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='provider_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
