# Generated by Django 4.2.9 on 2024-01-16 10:24

from django.db import migrations, models
import exports.enums


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0011_feasibility_study'),
        ('exports', '0006_remove_export_name_export_cohort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='request_job_duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='request_job_fail_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='request_job_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='request_job_status',
            field=models.CharField(choices=[('new', 'new'), ('denied', 'denied'), ('validated', 'validated'), ('pending', 'pending'), ('long_pending', 'long_pending'), ('started', 'started'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('cleaned', 'cleaned'), ('unknown', 'unknown')], default='new', max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='export',
            name='cohort_id',
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SENT_TO_DE', 'sent_to_dataexporter'), ('DELIVERED', 'delivered')], default=exports.enums.ExportStatus['PENDING'], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
