# Generated by Django 2.2.16 on 2022-04-28 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0010_auto_20220428_1314'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exports', '0006_auto_20220406_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='cohort_fk',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='export_requests', to='cohort.CohortResult'),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='creator_fk',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_export_requests',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='owner',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='export_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='reviewer_fk',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_export_requests',
                to=settings.AUTH_USER_MODEL),
        ),

        migrations.RenameField(
            model_name='exportrequest',
            old_name='export_request_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='exportrequest',
            old_name='deleted_at',
            new_name='cleaned_at',
        ),
        migrations.RenameField(
            model_name='exportrequest',
            old_name='request_datetime',
            new_name='insert_datetime',
        ),
        migrations.RenameField(
            model_name='exportrequest',
            old_name='validation_request_datetime',
            new_name='review_request_datetime',
        ),

        migrations.AddField(
            model_name='exportrequest',
            name='delete_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),

        migrations.AddField(
            model_name='exportrequest',
            name='new_request_job_status',
            field=models.CharField(choices=[
                ('new', 'new'), ('denied', 'denied'),
                ('validated', 'validated'), ('pending', 'pending'),
                ('started', 'started'), ('failed', 'failed'),
                ('cancelled', 'cancelled'), ('finished', 'finished'),
                ('cleaned', 'cleaned'), ('unknown', 'unknown')],
                default='pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='request_job_duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='request_job_fail_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='request_job_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='request_job_status',
            field=models.CharField(choices=[
                ('killed', 'killed'), ('finished', 'finished'),
                ('running', 'running'), ('started', 'started'),
                ('error', 'error'), ('unknown', 'unknown'),
                ('pending', 'pending')], default='pending', max_length=10,
                null=True),
        ),
    ]
