# Generated by Django 4.2.11 on 2024-04-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0007_export_request_job_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='status',
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='output_format',
            field=models.CharField(choices=[('csv', 'csv'), ('hive', 'hive')], max_length=20),
        ),
    ]
