# Generated by Django 2.2.16 on 2022-04-05 12:13
from enum import Enum
from typing import List

import django
from django.db import migrations, models

from exports.models import ExportRequest


class NewJobStatus(str, Enum):
    new = "new"
    denied = "denied"
    validated = "validated"
    pending = "pending"
    started = "started"
    failed = "failed"
    cancelled = "cancelled"
    finished = "finished"
    cleaned = "cleaned"
    unknown = "unknown"


def update_status(apps, schema_editor):
    MyExportRequest = apps.get_model('exports', 'ExportRequest')
    db_alias = schema_editor.connection.alias

    old_to_new = {
        'new': NewJobStatus.new,
        'validated': NewJobStatus.validated,
        'done': NewJobStatus.finished,
        'failed': NewJobStatus.failed,
        'denied': NewJobStatus.denied,
        'running': NewJobStatus.started,
        'canceled': NewJobStatus.cancelled,
        'to delete': NewJobStatus.unknown,
        'deleted': NewJobStatus.cleaned
    }

    ers: List[ExportRequest] = list(
        MyExportRequest.objects.using(db_alias).all())
    for er in ers:
        er.new_request_job_status = old_to_new.get(er.status,
                                                   NewJobStatus.unknown)
    MyExportRequest.objects.using(db_alias)\
        .bulk_update(ers, ['new_request_job_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0007_auto_20220428_1314'),
        ('admin_cohort', '0007_auto_20220331_1421'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE export_request er "
            "SET cohort_fk_id=("
            "SELECT uuid FROM cohort_cohortresult cr "
            "WHERE cr.fhir_group_id=CAST(er.cohort_id AS VARCHAR)"
            ")"
        ),
        migrations.RunSQL(
            'UPDATE export_request er '
            'SET creator_fk_id=('
            'SELECT u.provider_username FROM "user" u '
            'WHERE u.provider_id=er.provider_id'
            ')'
        ),
        migrations.RunSQL(
            'UPDATE export_request er '
            'SET owner_id=('
            'SELECT u.provider_username FROM "user" u '
            'WHERE u.provider_id=er.provider_id'
            ')'
        ),
        migrations.RunSQL(
            'UPDATE export_request '
            'SET request_job_fail_msg=status_info'
        ),
        migrations.RunPython(update_status),
        migrations.AlterField(
            model_name='exportrequesttable',
            name='export_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tables', to='exports.ExportRequest',
                to_field='id'),
        ),

    ]
