# Generated by Django 2.2.16 on 2022-04-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0008_manual_copy_foreignkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportrequest',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='exportrequest',
            name='creator_provider_source_value',
        ),
        migrations.RemoveField(
            model_name='exportrequest',
            name='provider_source_value',
        ),
        migrations.RemoveField(
            model_name='exportrequest',
            name='reviewer_id',
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportrequesttable',
            name='export_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tables', to='exports.ExportRequest'),
        ),
    ]
