# Generated by Django 2.2.16 on 2022-05-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0009_auto_20220428_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequest',
            name='shift_dates',
            field=models.BooleanField(default=False),
        ),
    ]
