# Generated by Django 4.2.11 on 2024-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0010_migrate_old_exports'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='use_one_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='export',
            name='output_format',
            field=models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx'), ('hive', 'hive')], max_length=20),
        ),
    ]
