# Generated by Django 2.2.16 on 2022-06-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0010_exportrequest_shift_dates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CohortDefinition',
        ),
    ]
