# Generated by Django 4.2.11 on 2024-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0011_add_xlsx_type_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportrequesttable',
            name='export_request',
        ),
        migrations.AlterField(
            model_name='export',
            name='output_format',
            field=models.CharField(choices=[('plain', 'plain')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ExportRequest',
        ),
        migrations.DeleteModel(
            name='ExportRequestTable',
        ),
    ]
