# Generated by Django 2.2.16 on 2022-09-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0012_manual_new_job_status_fill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportrequest',
            name='request_job_status',
        ),
        migrations.RemoveField(
            model_name='exportrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exportrequest',
            name='status_info',
        ),
        migrations.AlterField(
            model_name='exportrequest',
            name='new_request_job_status',
            field=models.CharField(choices=[
                ('new', 'new'), ('denied', 'denied'),
                ('validated', 'validated'), ('pending', 'pending'),
                ('started', 'started'), ('failed', 'failed'),
                ('cancelled', 'cancelled'), ('finished', 'finished'),
                ('cleaned', 'cleaned'), ('unknown', 'unknown')],
                default='new', max_length=10, null=True),
        ),
    ]
