# Generated by Django 5.0.8 on 2024-12-05 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0013_alter_export_output_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttable',
            name='columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, null=True, size=None),
        ),
    ]
