# Generated by Django 5.0.8 on 2024-08-27 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0016_fhirfilter_auto_generated_and_more'),
        ('exports', '0013_alter_export_output_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='cohort_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='cohort.cohortresult'),
        ),
    ]
