# Generated by Django 5.0.9 on 2025-02-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0014_exporttable_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttable',
            name='pivot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exporttable',
            name='pivot_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exporttable',
            name='pivot_split',
            field=models.BooleanField(default=False),
        ),
    ]
