# Generated by Django 2.2.28 on 2022-11-15 13:33

from django.db import migrations, models

STATUSES = [('new', 'new'), ('denied', 'denied'), ('validated', 'validated'),
            ('pending', 'pending'), ('started', 'started'), ('failed', 'failed'),
            ('cancelled', 'cancelled'), ('finished', 'finished'),
            ('cleaned', 'cleaned'), ('unknown', 'unknown')]


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0014_auto_20220916_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='request_job_status',
            field=models.CharField(choices=STATUSES, default='started', max_length=10, null=True),
        ),
    ]
