# Generated by Django 4.1.4 on 2022-12-26 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0015_auto_20221115_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exportrequesttable',
            options={},
        ),
    ]
