# Generated by Django 5.0.13 on 2025-04-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0015_exporttable_pivot_exporttable_pivot_merge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='retried',
            field=models.BooleanField(default=False),
        ),
    ]
