# Generated by Django 5.0.13 on 2025-04-23 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0016_export_retried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttable',
            name='pivot',
        ),
        migrations.RemoveField(
            model_name='exporttable',
            name='pivot_merge',
        ),
        migrations.RemoveField(
            model_name='exporttable',
            name='pivot_split',
        ),
        migrations.AddField(
            model_name='exporttable',
            name='pivot_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='exporttable',
            name='pivot_merge_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='exporttable',
            name='pivot_split_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
