# Generated by Django 4.1.4 on 2023-01-19 16:06

from django.db import migrations, models

STATUSES = [('new', 'new'), ('denied', 'denied'), ('validated', 'validated'), ('pending', 'pending'),
            ('long_pending', 'long_pending'), ('started', 'started'), ('failed', 'failed'),
            ('cancelled', 'cancelled'), ('finished', 'finished'), ('cleaned', 'cleaned'), ('unknown', 'unknown')]


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0016_alter_exportrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='request_job_status',
            field=models.CharField(choices=STATUSES, default='started', max_length=15, null=True),
        ),
    ]
