# Generated by Django 4.1.4 on 2023-02-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0017_alter_request_job_status_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='provider_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
