# Generated by Django 5.0.14 on 2025-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0017_remove_exporttable_pivot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttable',
            name='pivot_columns',
        ),
        migrations.RemoveField(
            model_name='exporttable',
            name='pivot_split_columns',
        ),
        migrations.AddField(
            model_name='exporttable',
            name='pivot_merge',
            field=models.BooleanField(default=False),
        ),
    ]
