# Generated by Django 5.0.14 on 2025-06-27 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0018_remove_exporttable_pivot_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttable',
            name='pivot_merge_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
