# Generated by Django 5.0.14 on 2025-07-17 12:39

import admin_cohort.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0019_exporttable_pivot_merge_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='request_job_duration',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='request_job_fail_msg',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='request_job_id',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='export',
            name='request_job_status',
            field=models.CharField(choices=[('new', 'new'), ('denied', 'denied'), ('validated', 'validated'), ('pending', 'pending'), ('long_pending', 'long_pending'), ('started', 'started'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('cleaned', 'cleaned'), ('unknown', 'unknown')], default=admin_cohort.types.JobStatus['new'], max_length=15),
        ),
    ]
