# Generated by Django 4.1.7 on 2023-05-03 15:20

from django.db import migrations, models

STATUSES = [('new', 'new'), ('denied', 'denied'), ('validated', 'validated'),
            ('pending', 'pending'), ('started', 'started'), ('failed', 'failed'),
            ('cancelled', 'cancelled'), ('finished', 'finished'),
            ('cleaned', 'cleaned'), ('unknown', 'unknown')]


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0019_alter_output_format_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='request_job_status',
            field=models.CharField(choices=STATUSES, default='new', max_length=15, null=True),
        ),
    ]
