# Generated by Django 5.0.14 on 2026-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0020_alter_string_based_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='request_job_type',
            field=models.TextField(blank=True),
        ),
    ]
