# Generated by Django 2.2.16 on 2022-03-30 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='shared_by',
            field=models.ForeignKey(
                default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shared_query_snapshots',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name', 'parent_folder')},
        ),
    ]
