# Generated by Django 2.2.16 on 2022-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_auto_20220330_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortresult',
            name='str_owner_id',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='str_owner_id',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='str_owner_id',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='str_owner_id',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='str_owner_id',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='str_shared_by_id',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
    ]
