# Generated by Django 4.1.7 on 2023-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_patch_perimeters_ids_in_rqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_status',
            field=models.CharField(
                choices=[('new', 'new'), ('denied', 'denied'), ('validated', 'validated'), ('pending', 'pending'), ('long_pending', 'long_pending'),
                         ('started', 'started'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('cleaned', 'cleaned'),
                         ('unknown', 'unknown')], default='new', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_job_status',
            field=models.CharField(
                choices=[('new', 'new'), ('denied', 'denied'), ('validated', 'validated'), ('pending', 'pending'), ('long_pending', 'long_pending'),
                         ('started', 'started'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('cleaned', 'cleaned'),
                         ('unknown', 'unknown')], default='new', max_length=15, null=True),
        ),
    ]
