# Generated by Django 2.2.16 on 2022-04-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0003_auto_20220405_1213'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE cohort_folder "
            "SET str_owner_id=CAST(owner_id AS VARCHAR)"
        ),
        migrations.RunSQL(
            "UPDATE cohort_request "
            "SET str_owner_id=CAST(owner_id AS VARCHAR)"
        ),
        migrations.RunSQL(
            "UPDATE cohort_requestquerysnapshot "
            "SET str_owner_id=CAST(owner_id AS VARCHAR), "
            "str_shared_by_id=CAST(shared_by_id AS VARCHAR)"
        ),
        migrations.RunSQL(
            "UPDATE cohort_datedmeasure "
            "SET str_owner_id=CAST(owner_id AS VARCHAR)"
        ),
        migrations.RunSQL(
            "UPDATE cohort_cohortresult "
            "SET str_owner_id=CAST(owner_id AS VARCHAR)"
        ),
    ]
