# Generated by Django 4.1.9 on 2023-06-26 09:41
import json

from django.db import migrations, models


def fill_in_version_in_snapshots(apps, schema_editor):
    request_model = apps.get_model('cohort', 'Request')
    db_alias = schema_editor.connection.alias

    request_list = request_model.objects.using(db_alias).all()
    for request in request_list:
        rqs_list = request.query_snapshots.all().order_by("created_at")
        version = 1
        for rqs in rqs_list:
            rqs.version = version
            rqs.save()
            version += 1


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_requestquerysnapshot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(fill_in_version_in_snapshots)
    ]
