# Generated by Django 2.2.16 on 2022-04-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_manual_copy_foreignkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortresult',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='datedmeasure',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='request',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='shared_by',
        ),
    ]
