# Generated by Django 4.1.7 on 2023-06-22 14:46

from django.db import migrations, models


def set_versions_for_old_query_snapshots(apps, schema_editor):
    request_model = apps.get_model('cohort', 'Request')
    db_alias = schema_editor.connection.alias

    for request in request_model.objects.using(db_alias).all():
        for i, rqs in enumerate(request.query_snapshots.all().order_by("created_at")):
            rqs.version = i + 1
            rqs.save()


def rollback_set_versions_for_old_query_snapshots(apps, schema_editor):
    rqs_model = apps.get_model('cohort', 'RequestQuerySnapshot')
    db_alias = schema_editor.connection.alias
    rqs_model.objects.using(db_alias).all().update(version=1)


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0004_requestquerysnapshot_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(set_versions_for_old_query_snapshots,
                             reverse_code=rollback_set_versions_for_old_query_snapshots),
    ]
