# Generated by Django 2.2.16 on 2022-04-05 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0005_auto_20220405_1216'),
        ('admin_cohort', '0006_manual_save_provider_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortresult',
            name='owner',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='user_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='owner',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='user_request_query_results',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='user_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='owner',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='user_request_query_snapshots',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='shared_by',
            field=models.ForeignKey(
                default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shared_query_snapshots',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
