# Generated by Django 2.2.16 on 2022-04-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0006_auto_20220405_1228'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE cohort_folder "
            "SET owner_id=str_owner_id"
        ),
        migrations.RunSQL(
            "UPDATE cohort_request "
            "SET owner_id=str_owner_id"
        ),
        migrations.RunSQL(
            "UPDATE cohort_requestquerysnapshot "
            "SET owner_id=str_owner_id, "
            "str_shared_by_id=CAST(shared_by_id AS VARCHAR)"
        ),
        migrations.RunSQL(
            "UPDATE cohort_datedmeasure "
            "SET owner_id=str_owner_id"
        ),
        migrations.RunSQL(
            "UPDATE cohort_cohortresult "
            "SET owner_id=str_owner_id"
        ),
    ]
