# Generated by Django 4.1.7 on 2023-09-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0006_fhirfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='dated_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='cohort.datedmeasure'),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='request_query_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort_results', to='cohort.requestquerysnapshot'),
        ),
    ]
