# Generated by Django 4.1.7 on 2023-09-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0006_fhirfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='is_active_branch',
        ),
    ]
