# Generated by Django 2.2.16 on 2022-04-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0007_auto_copy_foreignkeys_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_request_query_results',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestquerysnapshot',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_request_query_snapshots',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cohortresult',
            name='str_owner_id',
        ),
        migrations.RemoveField(
            model_name='datedmeasure',
            name='str_owner_id',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='str_owner_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='str_owner_id',
        ),
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='str_owner_id',
        ),
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='str_shared_by_id',
        ),
    ]
