# Generated by Django 4.1.7 on 2023-09-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0007_remove_snapshot_is_active_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='dated_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='cohort.datedmeasure'),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='dated_measure_global',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_cohorts', to='cohort.datedmeasure'),
        ),
    ]
