# Generated by Django 4.1.11 on 2023-11-23 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0008_alter_DM_related_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactRelationShip',
        ),
        migrations.AlterUniqueTogether(
            name='fhirfilter',
            unique_together={('fhir_resource', 'name', 'owner', 'deleted')},
        ),
    ]
