# Generated by Django 2.2.16 on 2022-04-28 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0008_auto_20220405_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='shared_by',
            field=models.ForeignKey(
                default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shared_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
