# Generated by Django 4.1.11 on 2023-11-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0009_delete_factrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='dated_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='cohort.datedmeasure'),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='request_query_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort_results', to='cohort.requestquerysnapshot'),
        ),
    ]
