# Generated by Django 4.1.11 on 2023-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0010_alter_cohortresult_DM_RQS_not_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='datedmeasure',
            name='feasibility_report',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
