# Generated by Django 4.1.11 on 2023-12-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0010_alter_cohortresult_DM_RQS_not_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityResult',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_count', models.IntegerField()),
                ('dated_measure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_result', to='cohort.datedmeasure')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeasibilityResultCount',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('perimeter_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('feasibility_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_result_counts', to='cohort.feasibilityresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='feasibilityresultcount',
            unique_together={('feasibility_result', 'perimeter_id')},
        )
    ]
