# Generated by Django 4.1.11 on 2023-12-22 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0010_alter_cohortresult_DM_RQS_not_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityStudy',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('request_job_id', models.TextField(blank=True, null=True)),
                ('request_job_status', models.CharField(choices=[('new', 'new'), ('denied', 'denied'), ('validated', 'validated'), ('pending', 'pending'), ('long_pending', 'long_pending'), ('started', 'started'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('finished', 'finished'), ('cleaned', 'cleaned'), ('unknown', 'unknown')], default='new', max_length=15, null=True)),
                ('request_job_fail_msg', models.TextField(blank=True, null=True)),
                ('request_job_duration', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('display_eligibility_criteria', models.BooleanField(default=False)),
                ('display_total_count', models.BooleanField(default=False)),
                ('display_count_by_ghu', models.BooleanField(default=False)),
                ('display_count_by_hospital', models.BooleanField(default=False)),
                ('display_count_by_uf', models.BooleanField(default=False)),
                ('display_visit_dates', models.BooleanField(default=False)),
                ('display_demographic_info', models.BooleanField(default=False)),
                ('display_repartition_graphs', models.BooleanField(default=False)),
                ('display_visit_graph', models.BooleanField(default=False)),
                ('display_demographic_graph', models.BooleanField(default=False)),
                ('report_json_content', models.BinaryField(blank=True, null=True)),
                ('report_file', models.BinaryField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_studies', to=settings.AUTH_USER_MODEL)),
                ('request_query_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_studies', to='cohort.requestquerysnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
