# Generated by Django 2.2.16 on 2022-05-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0011_set_new_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_fail_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_status',
            field=models.CharField(choices=[
                ('killed', 'killed'), ('finished', 'finished'),
                ('running', 'running'), ('started', 'started'),
                ('error', 'error'), ('unknown', 'unknown'),
                ('pending', 'pending')],
                default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_job_duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_job_fail_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_job_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_job_status',
            field=models.CharField(choices=[
                ('killed', 'killed'), ('finished', 'finished'),
                ('running', 'running'), ('started', 'started'),
                ('error', 'error'), ('unknown', 'unknown'),
                ('pending', 'pending')],
                default='pending', max_length=10, null=True),
        ),
    ]
