# Generated by Django 4.2.11 on 2024-05-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0012_cohortresult_is_subset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohortresult',
            old_name='fhir_group_id',
            new_name='group_id',
        ),
    ]
