# Generated by Django 4.2.11 on 2024-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0013_rename_fhir_group_id_cohortresult_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirfilter',
            name='query_version',
            field=models.CharField(default='v1.4.4', max_length=50),
        ),
    ]
