# Generated by Django 5.0.4 on 2024-07-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0014_requestrefreshschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='translated_query',
            field=models.TextField(null=True),
        ),
    ]
