# Generated by Django 5.0.4 on 2024-07-10 08:43

import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0014_fhirfilter_query_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='translated_query',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='RequestRefreshSchedule',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('refresh_time', models.TimeField()),
                ('refresh_frequency', models.CharField(choices=[('daily', 'daily'), ('every_other_day', 'every_other_day'), ('weekly', 'weekly')])),
                ('last_refresh', models.DateTimeField(null=True)),
                ('last_refresh_succeeded', models.BooleanField(null=True)),
                ('last_refresh_count', models.IntegerField(null=True)),
                ('last_refresh_error_msg', models.CharField(null=True)),
                ('notify_owner', models.BooleanField(default=False)),
                ('request_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_schedules', to='cohort.requestquerysnapshot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='requestrefreshschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('request_snapshot',), name='unique_request_snapshot_refresh_schedule'),
        ),
    ]
