# Generated by Django 5.0.8 on 2024-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0014_fhirfilter_query_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirfilter',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
