# Generated by Django 5.0.8 on 2024-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0015_requestrefreshschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirfilter',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestrefreshschedule',
            name='refresh_frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('every_other_day', 'every_other_day'), ('weekly', 'weekly')], default='weekly'),
        ),
    ]
