# Generated by Django 5.0.10 on 2025-01-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0016_fhirfilter_auto_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortresult',
            name='type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='data_type_of_query',
        ),
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='title',
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
