# Generated by Django 2.2.28 on 2022-11-02 07:55
from typing import List

from django.conf import settings
from django.db import migrations
from django.db.models import Count


def rename_duplicate_folders(apps, schema_editor):
    FolderModel = apps.get_model('cohort', 'Folder')
    db_alias = schema_editor.connection.alias

    duplicate_fodlers_data: List[FolderModel] = FolderModel.objects.using(db_alias).all().values("name", "owner_id")\
        .annotate(total=Count("name")).filter(total__gte=2)
    for item in duplicate_fodlers_data:
        folders_to_update = FolderModel.objects.using(db_alias).filter(name=item["name"], owner__id=item["owner_id"]).\
            order_by("created_at")
        for i, f in enumerate(folders_to_update[1:]):# do not update the first folder's name
            f.name = f"{f.name} ({i+1})"
            f.save()





class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0016_auto_20220916_1824'),
    ]

    operations = [
        migrations.RunPython(rename_duplicate_folders, reverse_code=rollback_duplicate_folders_names),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name')},
        ),
    ]
