# Generated by Django 5.0.10 on 2024-12-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0016_fhirfilter_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortresult',
            name='parent_cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_cohorts', to='cohort.cohortresult'),
        ),
        migrations.AddField(
            model_name='cohortresult',
            name='sampling_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
