# Generated by Django 2.2.28 on 2022-11-02 07:55
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0017_rename_duplicate_folders'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name')},
        ),
    ]
