# Generated by Django 2.2.28 on 2022-11-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0018_alter_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
    ]
