# Generated by Django 2.2.28 on 2022-11-04 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0018_auto_20221104_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('owner', 'name')},
        ),
    ]
