# Generated by Django 5.0.9 on 2025-03-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0018_remove_cohortresult_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datedmeasure',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
