# Generated by Django 5.0.13 on 2025-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0019_datedmeasure_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
