# Generated by Django 2.2.28 on 2022-11-15 13:33

from django.db import migrations, models

STATUSES = [('new', 'new'), ('denied', 'denied'), ('validated', 'validated'),
            ('pending', 'pending'), ('started', 'started'), ('failed', 'failed'),
            ('cancelled', 'cancelled'), ('finished', 'finished'),
            ('cleaned', 'cleaned'), ('unknown', 'unknown')]


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0019_remove_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortresult',
            name='request_job_status',
            field=models.CharField(choices=STATUSES, default='started', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='request_job_status',
            field=models.CharField(choices=STATUSES, default='started', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
    ]
