# Generated by Django 4.2.11 on 2024-07-03 08:06

from django.db import migrations, models


flag_filters_with_identifying_fields = """ UPDATE cohort_fhirfilter SET identifying=True 
                                           WHERE filter ilike '%family=%'
                                           OR filter ilike '%given=%'
                                           OR filter ilike '%identifier=%'
                                           OR filter ILIKE '%age-day=%'
                                           OR filter ilike '%subject.identifier=%'
                                           OR filter ilike '%encounter.identifier=%'
                                           OR filter ilike '%onlyPdfAvailable=%';
                                       """


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0020_requestquerysnapshot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirfilter',
            name='identifying',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(sql=flag_filters_with_identifying_fields),
    ]
