# Generated by Django 4.1.4 on 2022-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0020_auto_20221115_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactRelationShip',
            fields=[
                ('fact_relationship_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fact_id_1', models.BigIntegerField()),
                ('fact_id_2', models.BigIntegerField()),
            ],
            options={
                'db_table': 'fact_relationship',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='cohortresult',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='datedmeasure',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='request',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='requestquerysnapshot',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='cohortresult',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='datedmeasure',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='requestquerysnapshot',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
