# Generated by Django 2.2.28 on 2022-12-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0021_factrelationship_cohortresult_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='FactRelationShip',
            table='fact_relationship',
        ),
        migrations.RemoveField(
            model_name='FactRelationShip',
            name='fact_relationship_id',
        ),
        migrations.AlterUniqueTogether(
            name='FactRelationShip',
            unique_together={('fact_id_1', 'fact_id_2')},
        ),
    ]
