# Generated by Django 2.2.28 on 2022-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cohort', '0023_remove_measure_xxx_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='FactRelationShip',
            name='row_id',
            field=models.IntegerField(primary_key=True)
        )
    ]
