# Generated by Django 4.1.4 on 2023-01-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0023_alter_request_job_status_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datedmeasure',
            name='measure_alive',
        ),
        migrations.RemoveField(
            model_name='datedmeasure',
            name='measure_deceased',
        ),
        migrations.RemoveField(
            model_name='datedmeasure',
            name='measure_female',
        ),
        migrations.RemoveField(
            model_name='datedmeasure',
            name='measure_male',
        ),
        migrations.RemoveField(
            model_name='datedmeasure',
            name='measure_unknown',
        ),
    ]
