# Generated by Django 5.0.14 on 2026-04-03 15:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0024_filterfhirpatch'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fhirfilter',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
