# Generated by Django 5.0.14 on 2026-10-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0025_alter_fhirfilter_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirfilter',
            name='only_pdf_available',
            field=models.BooleanField(default=True),
        ),
    ]
