# Generated by Django 4.1.7 on 2023-03-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0025_factrelationship_row_id_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='refresh_create_cohort',
        ),
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='refresh_every_seconds',
        ),
        migrations.RemoveField(
            model_name='requestquerysnapshot',
            name='saved',
        ),
    ]
