# Generated by Django 2.2.28 on 2022-10-13 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSite',
            fields=[
                ('care_site_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('care_site_source_value', models.TextField(blank=True, null=True)),
                ('care_site_name', models.TextField(blank=True, null=True)),
                ('care_site_short_name', models.TextField(blank=True, null=True)),
                ('care_site_type_source_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'care_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_source_value', models.TextField()),
                ('valid_start_datetime', models.DateTimeField()),
                ('valid_end_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('insert_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('invalid_reason', models.TextField(blank=True, null=True)),
                ('right_edit_roles', models.BooleanField(default=False)),
                ('right_read_logs', models.BooleanField(default=False)),
                ('right_add_users', models.BooleanField(default=False)),
                ('right_edit_users', models.BooleanField(default=False)),
                ('right_read_users', models.BooleanField(default=False)),
                ('right_manage_admin_accesses_same_level', models.BooleanField(default=False)),
                ('right_read_admin_accesses_same_level', models.BooleanField(default=False)),
                ('right_manage_admin_accesses_inferior_levels', models.BooleanField(default=False)),
                ('right_read_admin_accesses_inferior_levels', models.BooleanField(default=False)),
                ('right_manage_data_accesses_same_level', models.BooleanField(default=False)),
                ('right_read_data_accesses_same_level', models.BooleanField(default=False)),
                ('right_manage_data_accesses_inferior_levels', models.BooleanField(default=False)),
                ('right_read_data_accesses_inferior_levels', models.BooleanField(default=False)),
                ('right_read_patient_nominative', models.BooleanField(default=False)),
                ('right_read_patient_pseudo_anonymised', models.BooleanField(default=False)),
                ('right_search_patient_with_ipp', models.BooleanField(default=False)),
                ('right_manage_review_transfer_jupyter', models.BooleanField(default=False)),
                ('right_review_transfer_jupyter', models.BooleanField(default=False)),
                ('right_manage_transfer_jupyter', models.BooleanField(default=False)),
                ('right_transfer_jupyter_nominative', models.BooleanField(default=False)),
                ('right_transfer_jupyter_pseudo_anonymised', models.BooleanField(default=False)),
                ('right_manage_review_export_csv', models.BooleanField(default=False)),
                ('right_review_export_csv', models.BooleanField(default=False)),
                ('right_manage_export_csv', models.BooleanField(default=False)),
                ('right_export_csv_nominative', models.BooleanField(default=False)),
                ('right_export_csv_pseudo_anonymised', models.BooleanField(default=False)),
                ('right_read_env_unix_users', models.BooleanField(default=False)),
                ('right_manage_env_unix_users', models.BooleanField(default=False)),
                ('right_manage_env_user_links', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('insert_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_id', models.BigIntegerField(blank=True, null=True)),
                ('provider_name', models.TextField(blank=True, null=True)),
                ('firstname', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, default='Manual', null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('manual_is_active', models.BooleanField(blank=True, null=True)),
                ('valid_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('manual_valid_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('valid_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('manual_valid_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perimeter',
            fields=[
                ('insert_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('local_id', models.CharField(max_length=63, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('source_value', models.TextField(blank=True, null=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('type_source_value', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='children', to='accesses.Perimeter')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('insert_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(blank=True, default='Manual', null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('manual_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('manual_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('perimeter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='accesses', to='accesses.Perimeter')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='accesses', to='accesses.Profile')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='accesses', to='accesses.Role')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
