# Generated by Django 4.1.7 on 2023-05-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_read_opposing_patient',
            field=models.BooleanField(default=False),
        ),
    ]
