# Generated by Django 2.2.16 on 2021-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_read_logs',
            field=models.BooleanField(default=False),
        ),
    ]
