# Generated by Django 2.2.16 on 2021-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0002_role_right_read_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_export_csv_nominative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_export_csv_pseudo_anonymised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_manage_export_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_manage_review_export_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_manage_review_transfer_jupyter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_manage_transfer_jupyter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_review_export_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_review_transfer_jupyter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_transfer_jupyter_nominative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_transfer_jupyter_pseudo_anonymised',
            field=models.BooleanField(default=False),
        ),
    ]
