# Generated by Django 4.1.7 on 2023-07-25 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accesses', '0002_add_opposing_patient_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accesses',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='access',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accesses',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
