# Generated by Django 2.2.13 on 2021-05-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0003_auto_20211201_1559'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE role req SET right_export_csv_nominative=true "
            "WHERE right_export_jupyter_patient_nominative;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "UPDATE role req "
            "SET right_export_csv_pseudo_anonymised=true "
            "WHERE right_export_jupyter_patient_pseudo_anonymised;",
            reverse_sql=""
        ),
    ]
