# Generated by Django 4.1.7 on 2023-07-28 13:37

from django.db import migrations, models


APHP_ID = 8312002244


def compute_perimeters_levels(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    perimeter_model = apps.get_model('accesses', 'Perimeter')
    aphp = perimeter_model.objects.using(db_alias).get(id=APHP_ID)
    top_level = 1

    def set_level_for_child_perimeters(perimeter, level):
        perimeter.level = level
        perimeter.save()
        level += 1
        for child in perimeter.children.all():
            set_level_for_child_perimeters(perimeter=child, level=level)

    set_level_for_child_perimeters(perimeter=aphp, level=top_level)


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0004_set_created_by_updated_by_for_accesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(code=compute_perimeters_levels),
    ]
