# Generated by Django 4.1.7 on 2023-07-28 13:37

from django.db import migrations, models


APHP_ID = 8312002244

trim_trailing_commas = "UPDATE accesses_perimeter SET above_levels_ids=TRIM(trailing ',' from above_levels_ids)"
set_level_aphp = f"UPDATE accesses_perimeter SET level=1 WHERE id = {APHP_ID}"
set_level_other_perimeters = f"""UPDATE accesses_perimeter SET level=array_length(string_to_array(above_levels_ids, ','), 1)+1 
                                 WHERE id <> {APHP_ID} AND above_levels_ids IS NOT NULL"""


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0004_set_created_by_updated_by_for_accesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(sql=trim_trailing_commas),
        migrations.RunSQL(sql=set_level_aphp),
        migrations.RunSQL(sql=set_level_other_perimeters),
    ]
