# Generated by Django 2.2.16 on 2021-12-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0004_auto_20211201_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_manage_env_unix_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_manage_env_user_apps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_manage_env_user_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_read_env_unix_users',
            field=models.BooleanField(default=False),
        ),
    ]
