# Generated by Django 4.1.7 on 2023-07-28 13:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0005_perimeter_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='allowed_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='allowed_users_above_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='allowed_users_inferior_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
    ]
