# Generated by Django 2.2.16 on 2021-12-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0005_auto_20211202_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSite',
            fields=[
                ('insert_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('update_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('delete_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('hash', models.IntegerField(blank=True)),
                ('change_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('care_site_id', models.BigIntegerField(primary_key=True,
                                                        serialize=False)),
                ('care_site_source_value', models.TextField(blank=True,
                                                            null=True)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('care_site_name', models.TextField(blank=True, null=True)),
                ('care_site_short_name', models.TextField(blank=True,
                                                          null=True)),
                ('place_of_service_concept_id', models.IntegerField(blank=True,
                                                                    null=True)),
                ('place_of_service_source_value', models.TextField(blank=True,
                                                                   null=True)),
                ('place_of_service_source_concept_id',
                 models.IntegerField(blank=True, null=True)),
                ('valid_start_date', models.DateField(blank=True, null=True)),
                ('valid_end_date', models.DateField(blank=True, null=True)),
                ('care_site_type_concept_id', models.IntegerField(blank=True,
                                                                  null=True)),
                ('care_site_type_source_value', models.TextField(blank=True,
                                                                 null=True)),
                ('care_site_type_source_concept_id',
                 models.IntegerField(blank=True, null=True)),
                ('cdm_source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'care_site',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id',
                 models.IntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concept',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FactRelationship',
            fields=[
                ('insert_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('update_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('delete_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('domain_concept_id_1', models.IntegerField()),
                ('fact_id_1', models.BigIntegerField()),
                ('domain_concept_id_2', models.IntegerField()),
                ('fact_id_2', models.BigIntegerField()),
                ('relationship_concept_id', models.IntegerField()),
                ('fact_relationship_id', models.AutoField(primary_key=True,
                                                          serialize=False)),
                ('change_datetime', models.DateTimeField(blank=True,
                                                         null=True)),
                ('cdm_source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_relationship',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender_concept_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender_source_concept_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender_source_value',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialty_concept_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialty_source_concept_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialty_source_value',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_of_birth',
        ),
    ]
