# Generated by Django 2.2.16 on 2021-12-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0006_auto_20211229_1441'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='access',
            table='access',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
