# Generated by Django 2.2.16 on 2022-02-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0007_auto_20211229_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareSite',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='FactRelationship',
        ),
    ]
