# Generated by Django 4.1.7 on 2023-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0008_remove_access_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_read_admin_accesses_above_levels',
            field=models.BooleanField(default=False),
        ),
    ]
