# Generated by Django 4.1.7 on 2023-08-19 15:42

from django.db import migrations


def compute_allowed_users_above_levels(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    perimeter_model = apps.get_model('accesses', 'Perimeter')

    for perimeter in perimeter_model.objects.using(db_alias).all():
        parents_ids = perimeter.above_levels_ids and (int(i) for i in perimeter.above_levels_ids.split(",") if i) or []
        parents_chain = perimeter_model.objects.using(db_alias).filter(id__in=parents_ids)
        perimeter.allowed_users_above_levels = list(set(sum([p.allowed_users for p in parents_chain], [])))
        perimeter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0008_remove_access_end_datetime_and_more'),
    ]

    operations = [
        migrations.RunPython(code=compute_allowed_users_above_levels),
    ]
