# Generated by Django 2.2.16 on 2022-04-07 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accesses', '0008_auto_20220210_1509'),
        ('admin_cohort', '0005_auto_20220331_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='care_site_history_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='care_site_id',
            new_name='perimeter_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='provider_history_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='access',
            name='care_site_history_type_source_value',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='cdm_source',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='access',
            name='domain_id',
        ),
        migrations.RemoveField(
            model_name='access',
            name='relationship_type_concept_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cdm_source',
            new_name='source',
        ),

        migrations.RemoveField(
            model_name='profile',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified_datetime',
        ),

        migrations.AddField(
            model_name='access',
            name='profile',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='accesses', to='accesses.Profile'),
        ),
        migrations.AddField(
            model_name='access',
            name='role_fk',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='accesses', to='accesses.Role'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='access',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
