# Generated by Django 4.1.11 on 2023-10-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0009_role_right_read_admin_accesses_above_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='right_transfer_jupyter_nominative',
            new_name='right_export_jupyter_nominative',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_transfer_jupyter_pseudo_anonymised',
            new_name='right_export_jupyter_pseudonymized',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_manage_export_csv',
            new_name='right_manage_export_csv_accesses',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_manage_transfer_jupyter',
            new_name='right_manage_export_jupyter_accesses',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_review_export_csv',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_review_transfer_jupyter',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_review_export_csv',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_review_transfer_jupyter',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_search_patient_with_ipp',
            new_name='right_search_patients_by_ipp',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_read_admin_accesses_above_levels',
            new_name='right_read_accesses_above_levels',
        ),
    ]
