# Generated by Django 4.1.11 on 2023-11-03 11:58

from django.db import migrations, models

query_fill_right_full_admin_by_right_manage_roles = "UPDATE accesses_role SET right_full_admin = right_manage_roles;"


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0009_role_right_read_admin_accesses_above_levels'),
    ]

    operations = [
        migrations.AddField(     # ---------------------------------------   NEW
            model_name='role',
            name='right_full_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='right_read_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(     # ---------------------------------------   RENAMED
            model_name='role',
            old_name='right_add_users',
            new_name='right_manage_users',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_edit_roles',
            new_name='right_manage_roles',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_read_admin_accesses_above_levels',
            new_name='right_read_accesses_above_levels',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_read_patient_pseudo_anonymised',
            new_name='right_read_patient_pseudonymized',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_export_csv_pseudo_anonymised',
            new_name='right_export_csv_pseudonymized',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_manage_export_csv',
            new_name='right_manage_export_csv_accesses',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_manage_transfer_jupyter',
            new_name='right_manage_export_jupyter_accesses',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_transfer_jupyter_nominative',
            new_name='right_export_jupyter_nominative',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_transfer_jupyter_pseudo_anonymised',
            new_name='right_export_jupyter_pseudonymized',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_manage_env_unix_users',
            new_name='right_manage_datalabs',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_read_env_unix_users',
            new_name='right_read_datalabs',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_search_patient_with_ipp',
            new_name='right_search_patients_by_ipp',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='right_read_opposing_patient',
            new_name='right_read_research_opposed_patient_data',
        ),
        migrations.RunSQL(sql=query_fill_right_full_admin_by_right_manage_roles),
    ]
