# Generated by Django 4.1.11 on 2023-11-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0009_role_right_read_admin_accesses_above_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactRelationShip',
            fields=[
                ('row_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fact_id_1', models.BigIntegerField()),
                ('fact_id_2', models.BigIntegerField()),
            ],
            options={
                'db_table': 'fact_relationship',
                'managed': False,
            },
        ),
    ]
