# Generated by Django 2.2.16 on 2022-04-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0011_auto_20220408_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='role_fk',
            new_name='role',
        ),
    ]
