# Generated by Django 4.1.11 on 2023-11-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0011_add_new_rights_and_rename_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='right_edit_roles',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_edit_users',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_env_user_links',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_review_export_csv',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_review_transfer_jupyter',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_review_export_csv',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_review_transfer_jupyter',
        ),
        migrations.RemoveField(
            model_name='role',
            name='invalid_reason',
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_datetime__isnull', True)), fields=('name',), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_datetime__isnull', True)), fields=(
            'right_full_admin', 'right_read_logs', 'right_manage_users', 'right_read_users',
            'right_manage_datalabs', 'right_read_datalabs', 'right_export_csv_nominative', 'right_export_csv_pseudonymized',
            'right_export_jupyter_nominative', 'right_export_jupyter_pseudonymized', 'right_manage_export_csv_accesses',
            'right_manage_export_jupyter_accesses', 'right_read_patient_nominative', 'right_read_patient_pseudonymized',
            'right_search_patients_by_ipp', 'right_search_opposed_patients', 'right_manage_data_accesses_same_level',
            'right_read_data_accesses_same_level', 'right_manage_data_accesses_inferior_levels', 'right_read_data_accesses_inferior_levels',
            'right_manage_admin_accesses_same_level', 'right_read_admin_accesses_same_level', 'right_manage_admin_accesses_inferior_levels',
            'right_read_admin_accesses_inferior_levels', 'right_read_accesses_above_levels'), name='unique_rights_combination'),
        ),
    ]
