# Generated by Django 4.2.10 on 2024-03-08 09:23
import logging

from django.db import migrations, models
import django.db.models.deletion

from accesses.data.rights import right_categories, dependent_rights
from accesses.serializers import RightCategorySerializer


_logger = logging.getLogger('info')


def load_rights(apps, schema_editor):
    right_model = apps.get_model('accesses', 'Right')
    db_alias = schema_editor.connection.alias

    rc_serializer = RightCategorySerializer(data=right_categories, many=True)
    if rc_serializer.is_valid():
        rc_serializer.save()
    else:
        _logger.error(f"Serializer errors: {rc_serializer.errors}")
        return

    for r in dependent_rights:
        depends_on = right_model.objects.using(db_alias).get(name=r.get('depends_on'))
        r.update({"depends_on": depends_on,
                  "category": depends_on.category
                  })
        right_model.objects.using(db_alias).create(**r)


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0012_remove_old_rights_add_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightCategory',
            fields=[
                ('insert_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('is_global', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('insert_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('label', models.CharField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights', to='accesses.rightcategory')),
                ('depends_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_rights', to='accesses.right')),
                ('allow_read_accesses_on_same_level', models.BooleanField(null=True, default=False)),
                ('allow_read_accesses_on_inf_levels', models.BooleanField(null=True, default=False)),
                ('allow_edit_accesses_on_same_level', models.BooleanField(null=True, default=False)),
                ('allow_edit_accesses_on_inf_levels', models.BooleanField(null=True, default=False)),
                ('impact_inferior_levels', models.BooleanField(null=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(code=load_rights)
    ]
