# Generated by Django 2.2.16 on 2022-04-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0012_auto_20220408_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perimeter',
            fields=[
                ('id', models.BigIntegerField(primary_key=True,
                                              serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('source_value', models.TextField(blank=True, null=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('type_source_value', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='children', to='accesses.Perimeter')),
            ],
            options={
                'db_table': 'portail_care_site',
                'managed': True,
            },
        ),
    ]
