# Generated by Django 4.2.10 on 2024-03-08 09:23
import logging

from django.db import migrations, models
import django.db.models.deletion

from accesses.migrations.data.rights import rights, dependent_rights
from accesses.serializers import RightSerializer


_logger = logging.getLogger('info')


def load_rights(apps, schema_editor):
    for data_set in (rights, dependent_rights):
        right_serializer = RightSerializer(data=data_set, many=True)
        if right_serializer.is_valid():
            right_serializer.save()
        else:
            _logger.error(f"Error on loading initial rights data: {right_serializer.errors}")
            return


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0013_remove_profile_email_remove_profile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('insert_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('delete_datetime', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('label', models.CharField()),
                ('is_global', models.BooleanField(default=False)),
                ('category', models.CharField()),
                ('depends_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_rights', to='accesses.right')),
                ('allow_read_accesses_on_same_level', models.BooleanField(null=True, default=False)),
                ('allow_read_accesses_on_inf_levels', models.BooleanField(null=True, default=False)),
                ('allow_edit_accesses_on_same_level', models.BooleanField(null=True, default=False)),
                ('allow_edit_accesses_on_inf_levels', models.BooleanField(null=True, default=False)),
                ('impact_inferior_levels', models.BooleanField(null=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(code=load_rights)
    ]
