# Generated by Django 2.2.16 on 2022-06-16 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0013_auto_20220419_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='delete_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='local_id',
            field=models.CharField(max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='access',
            table=None,
        ),
        migrations.AlterModelTable(
            name='perimeter',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
        migrations.RunSQL(
            "UPDATE accesses_perimeter p "
            "SET local_id=CAST(p.id AS VARCHAR);",
            reverse_sql=""
        ),
    ]
