# Generated by Django 2.2.16 on 2022-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0014_auto_20220616_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perimeter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perimeter',
            name='local_id',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
