# Generated by Django 4.2.10 on 2024-03-08 09:23
import logging

from django.db import migrations, models
import django.db.models.deletion

from accesses.migrations.data.rights import rights, dependent_rights
from accesses.serializers import RightSerializer

_logger = logging.getLogger('info')


class Migration(migrations.Migration):
    dependencies = [
        ('accesses', '0014_rightcategory_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_search_patients_unlimited',
            field=models.BooleanField(default=False)
        ),
    ]
