# Generated by Django 4.2.11 on 2024-06-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0015_add_full_data_access_right'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manual_is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manual_valid_end_datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='manual_valid_start_datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='valid_end_datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='valid_start_datetime',
        ),
    ]
