# Generated by Django 5.0.4 on 2024-07-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0015_add_full_data_access_right'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareSite',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='FactRelationShip',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
