# Generated by Django 2.2.16 on 2022-06-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0015_auto_20220616_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='perimeter_fk',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='accesses', to='accesses.Perimeter',
                to_field='id'),
        ),
        migrations.RunSQL(
            "UPDATE accesses_access a "
            "SET perimeter_fk_id=a.perimeter_id "
            "WHERE a.perimeter_id IN (SELECT id FROM accesses_perimeter);",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "UPDATE accesses_access a "
            "SET perimeter_fk_id=null, perimeter_id=null "
            "WHERE a.perimeter_id NOT IN (SELECT id FROM accesses_perimeter);",
            reverse_sql=""
        ),
    ]
