# Generated by Django 2.2.16 on 2022-06-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0016_access_perimeter_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='perimeter_id',
        ),
        migrations.RenameField(
            model_name='access',
            old_name='perimeter_fk',
            new_name='perimeter',
        ),
    ]
