# Generated by Django 5.0.4 on 2024-07-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0016_delete_provider_remove_fields_from_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareSite',
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='FactRelationShip',
        )
    ]
