# Generated by Django 2.2.16 on 2022-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0017_auto_20220616_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_search_patient_with_ipp',
            field=models.BooleanField(default=False),
        ),
    ]
