# Generated by Django 5.0.11 on 2025-02-12 14:44
import logging

from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger(__name__)

ORBIS = settings.ACCESS_SOURCES[1]


def delete_existing_orbis_profiles(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    profile_model = apps.get_model('accesses', 'Profile')
    deleted_count, _ = profile_model.objects.using(db_alias).filter(source=ORBIS).delete()
    logger.info(f"Deleted {deleted_count} old profiles with source `ORBIS`")


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0017_delete_caresite_delete_concept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='right_read_practitioner_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='external_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RunPython(code=delete_existing_orbis_profiles, reverse_code=migrations.RunPython.noop),
    ]
