# Generated by Django 5.0.14 on 2025-06-20 14:53
import logging

from django.db import migrations

from accesses.data.new_rights import rights, dependent_rights
from accesses.serializers import RightSerializer


logger = logging.getLogger(__name__)


delete_old_rights = "DELETE FROM accesses_right WHERE True;"

adjust_accesses_mgmt_roles =  """ UPDATE accesses_role
                                  SET right_read_accesses_above_levels = True
                                  WHERE right_manage_admin_accesses_same_level = True
                                     OR right_manage_admin_accesses_inferior_levels = True
                                     OR right_manage_data_accesses_same_level = True
                                     OR right_manage_data_accesses_inferior_levels = True;
                              """


def load_new_rights(apps, schema_editor):
    for data_set in (rights, dependent_rights):
        right_serializer = RightSerializer(data=data_set, many=True)
        if right_serializer.is_valid():
            right_serializer.save()
        else:
            logger.error(f"Error on loading rights: {right_serializer.errors}")
            return


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0018_add_orbis_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='right_export_csv_nominative',
            new_name='right_export_csv_xlsx_nominative',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_export_csv_pseudonymized',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_export_csv_accesses',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_export_jupyter_accesses',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_admin_accesses_inferior_levels',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_admin_accesses_same_level',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_data_accesses_inferior_levels',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_data_accesses_same_level',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_logs',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_users',
        ),
        migrations.RemoveField(
            model_name='right',
            name='allow_read_accesses_on_inf_levels',
        ),
        migrations.RemoveField(
            model_name='right',
            name='allow_read_accesses_on_same_level',
        ),
        migrations.RunSQL(sql=delete_old_rights, reverse_sql=migrations.RunSQL.noop),
        migrations.RunPython(code=load_new_rights, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(sql=adjust_accesses_mgmt_roles, reverse_sql=migrations.RunSQL.noop)
    ]
