# Generated by Django 5.0.14 on 2025-06-20 14:53
import logging

from django.db import migrations

from accesses.serializers import RightSerializer


logger = logging.getLogger(__name__)


delete_old_rights = "DELETE FROM accesses_right WHERE True;"

adjust_accesses_mgmt_roles =  """ UPDATE accesses_role
                                  SET right_read_accesses_above_levels = True
                                  WHERE right_manage_admin_accesses_same_level = True
                                     OR right_manage_admin_accesses_inferior_levels = True
                                     OR right_manage_data_accesses_same_level = True
                                     OR right_manage_data_accesses_inferior_levels = True;
                              """

rights = [
    {
        "name": "right_full_admin",
        "label": "Administrateur",
        "category": "Administration",
        "is_global": True,
    },
    {
        "name": "right_manage_users",
        "label": "Gérer la liste des utilisateurs",
        "category": "Utilisateurs",
        "is_global": True,
    },
    {
        "label": "Gérer les accès aux données patient d'un périmètre exclusivement",
        "name": "right_manage_data_accesses_same_level",
        "allow_edit_accesses_on_same_level": True,
        "category": "Gestion des Accès Données",
        "is_global": False,
    },
    {
        "label": "Gérer les accès aux données patient des sous-périmètres exclusivement",
        "name": "right_manage_data_accesses_inferior_levels",
        "allow_edit_accesses_on_inf_levels": True,
        "impact_inferior_levels": True,
        "category": "Gestion des Accès Données",
        "is_global": False,
    },
    {
        "label": "Gérer les accès administrateurs d'un périmètre exclusivement",
        "name": "right_manage_admin_accesses_same_level",
        "allow_edit_accesses_on_same_level": True,
        "category": "Gestion des Accès Administrateurs",
        "is_global": False,
    },
    {
        "label": "Gérer les accès administrateurs des sous-périmètres exclusivement",
        "name": "right_manage_admin_accesses_inferior_levels",
        "allow_edit_accesses_on_inf_levels": True,
        "impact_inferior_levels": True,
        "category": "Gestion des Accès Administrateurs",
        "is_global": False,
    },
    {
        "label": "Lecture de données patient nominatives",
        "name": "right_read_patient_nominative",
        "impact_inferior_levels": True,
        "category": "Lecture de Données Patient",
        "is_global": False,
    },
    {
        "label": "Lecture de données patient pseudonymisées",
        "name": "right_read_patient_pseudonymized",
        "impact_inferior_levels": True,
        "category": "Lecture de Données Patient",
        "is_global": False,
    },
    {
        "label": "Chercher les patients par IPP",
        "name": "right_search_patients_by_ipp",
        "category": "Recherche de Patients",
        "is_global": True,
    },
    {
        "label": "Chercher les patients sans limite de périmètre (PP)",
        "name": "right_search_patients_unlimited",
        "category": "Recherche de Patients",
        "is_global": True,
    },
    {
        "label": "Chercher les patients opposés à l'utilisation de leurs données pour la recherche",
        "name": "right_search_opposed_patients",
        "category": "Recherche de Patients",
        "is_global": True,
    },
    {
        "label": "Exporter ses cohortes de patients sous forme nominative vers un environnement Jupyter",
        "name": "right_export_jupyter_nominative",
        "category": "Exports Jupyter",
        "is_global": True,
    },
    {
        "label": "Exporter ses cohortes de patients sous forme pseudonymisée vers un environnement Jupyter",
        "name": "right_export_jupyter_pseudonymized",
        "category": "Exports Jupyter",
        "is_global": True,
    },
    {
        "label": "Exporter ses cohortes de patients sous forme nominative en format CSV-Excel",
        "name": "right_export_csv_xlsx_nominative",
        "category": "Exports CSV-Excel",
        "is_global": True,
    },
    {
        "label": "Consulter les accès en provenance des périmètres parents",
        "name": "right_read_accesses_above_levels",
        "category": "Divers",
        "is_global": True,
    },
    {
        "name": "right_manage_datalabs",
        "label": "Gérer la liste des datalabs",
        "category": "Datalabs",
        "is_global": True,
    },
]

dependent_rights = [
    {
        "name": "right_read_datalabs",
        "label": "Consulter la liste des datalabs",
        "category": "Datalabs",
        "is_global": True,
        "depends_on": "right_manage_datalabs",
    },
]


def load_new_rights(apps, schema_editor):
    for data_set in (rights, dependent_rights):
        right_serializer = RightSerializer(data=data_set, many=True)
        if right_serializer.is_valid():
            right_serializer.save()
        else:
            logger.error(f"Error on loading rights: {right_serializer.errors}")
            return


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0018_add_orbis_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='right_export_csv_nominative',
            new_name='right_export_csv_xlsx_nominative',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_export_csv_pseudonymized',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_export_csv_accesses',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_export_jupyter_accesses',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_admin_accesses_inferior_levels',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_admin_accesses_same_level',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_data_accesses_inferior_levels',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_data_accesses_same_level',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_logs',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_read_users',
        ),
        migrations.RemoveField(
            model_name='right',
            name='allow_read_accesses_on_inf_levels',
        ),
        migrations.RemoveField(
            model_name='right',
            name='allow_read_accesses_on_same_level',
        ),
        migrations.RunSQL(sql=delete_old_rights, reverse_sql=migrations.RunSQL.noop),
        migrations.RunPython(code=load_new_rights, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(sql=adjust_accesses_mgmt_roles, reverse_sql=migrations.RunSQL.noop)
    ]
