# Generated by Django 2.2.16 on 2022-06-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0018_auto_20220628_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='right_export_jupyter_patient_nominative',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_export_jupyter_patient_pseudo_anonymised',
        ),
        migrations.RemoveField(
            model_name='role',
            name='right_manage_env_user_apps',
        ),
    ]
