# Generated by Django 2.2.28 on 2022-10-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0019_auto_20220628_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSite',
            fields=[
                ('care_site_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('care_site_source_value', models.TextField(blank=True, null=True)),
                ('care_site_name', models.TextField(blank=True, null=True)),
                ('care_site_short_name', models.TextField(blank=True, null=True)),
                ('care_site_type_source_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'care_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_source_value', models.TextField()),
                ('valid_start_datetime', models.DateTimeField()),
                ('valid_end_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'provider',
                'managed': False,
            },
        ),
    ]
