# Generated by Django 5.0.14 on 2025-07-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0019_remove_multiple_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='right_read_accesses_above_levels',
        ),
        migrations.RunSQL(sql="DELETE FROM accesses_right WHERE name='right_read_accesses_above_levels';",
                          reverse_sql=migrations.RunSQL.noop),
    ]
