# Generated by Django 2.2.28 on 2022-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0019_auto_20220628_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='above_levels_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perimeter',
            name='bellow_levels_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
