# Generated by Django 2.2.16 on 2022-06-16 13:26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0020_caresite_concept_provider'),
    ]
    operations = [
        migrations.AddField(
            model_name='Perimeter',
            name='above',
            field=models.TextField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='Perimeter',
            name='lower_levels',
            field=models.TextField(blank=True, null=True)
        ),
    ]
