# Generated by Django 2.2.28 on 2022-10-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accesses', '0020_auto_20221026_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='full_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
