# Generated by Django 5.0.14 on 2025-07-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0020_remove_role_right_read_accesses_above_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='right_read_practitioner_data',
        ),
    ]
