# Generated by Django 2.2.28 on 2022-11-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0021_auto_20221027_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perimeter',
            old_name='bellow_levels_ids',
            new_name='inferior_levels_ids',
        ),
    ]
