# Generated by Django 2.2.28 on 2022-11-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accesses', '0022_auto_20221102_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimeter',
            name='cohort_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
