# Generated by Django 4.1.4 on 2022-12-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0025_patch_users_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSite',
            fields=[
                ('care_site_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('care_site_source_value', models.TextField(blank=True, null=True)),
                ('care_site_name', models.TextField(blank=True, null=True)),
                ('care_site_short_name', models.TextField(blank=True, null=True)),
                ('care_site_type_source_value', models.TextField(blank=True, null=True)),
                ('care_site_parent_id', models.BigIntegerField(null=True)),
                ('cohort_id', models.BigIntegerField(null=True)),
                ('cohort_size', models.BigIntegerField(null=True)),
                ('delete_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'care_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('concept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('concept_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_source_value', models.TextField()),
                ('valid_start_datetime', models.DateTimeField()),
                ('valid_end_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'provider',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='access',
            name='perimeter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesses', to='accesses.perimeter'),
        ),
    ]
