# Generated by Django 4.1.4 on 2023-02-07 10:46

from django.db import migrations, models

from accesses.models import Profile


def update_provider_id_by_user_id(apps, schema_editor):
    profiles = Profile.objects.all()
    for profile in profiles:
        profile.provider_id = profile.user_id
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accesses", "0026_caresite_concept_provider_alter_access_perimeter"),
    ]
    operations = [
        migrations.AlterField(
            model_name="profile",
            name="provider_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.RunPython(update_provider_id_by_user_id),
    ]
