# Generated by Django 4.1.6 on 2023-02-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0027_alter_profile_provider_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perimeter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='access',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
    ]
