name: main

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Ruff
        run: uv tool run ruff check .
      
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Safety
        run: uv tool run safety check -i 42240,66963,70612,65213

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13
      - name: MyPy
        run: uv tool run mypy admin_cohort accesses cohort

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Bandit
        run: uv tool run bandit -r . -x tests,migrations

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Deptry
        run: uv tool run deptry .
      
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Check
        run: uv run python manage.py check --deploy

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: portail_test
          POSTGRES_USER: portail_dev_limited_rw
          POSTGRES_PASSWORD: portail_psswd
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U portail_dev_limited_rw -d portail_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install UV
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Install system deps
        run: |
          sudo apt-get update && sudo apt-get -y install gcc libkrb5-dev
          sudo locale-gen fr_FR.utf8
          sudo update-locale

      - name: Install project dependencies
        run: uv sync

      - name: Create logs dir
        run: mkdir log

      - name: Run Django migrations
        run: |
          cp .conf/.test.env .env
          uv run python manage.py migrate

      - name: Run tests
        run: |
          uv run coverage run --source='.' --omit="*/test*","*/migrations/*" manage.py test
          uv run coverage xml --omit="*/test*","*/migrations/*" -o coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage.xml

  sonar:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'run-sonar')
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download coverage report
        uses: actions/download-artifact@v8
        with:
          name: coverage-report

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main' ||
      startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Retrieve version
        run: |
          VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = "(.*)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compute Docker tags
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo "IMAGE_TAGS=aphpid/cohort360-backend:${VERSION},aphpid/cohort360-backend:latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAGS=aphpid/cohort360-backend:${VERSION}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: aphpid/cohort360-backend:${{ env.IMAGE_TAGS }}