name: dependency_safety

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install system deps
        run: sudo apt-get -y install gcc libkrb5-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linter
        run: |
          pip install ruff
          ruff check .
      - name: Run safety check
        run: |
          pip install safety
          safety check -i 42240
